name: Feature request
description: Suggest an idea or improvement
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem would this feature solve?
      placeholder: I want to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your preferred solution.
      placeholder: It would be great if...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you've thought about?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, or examples.
    validations:
      required: false
